Beta8
ReFlar/level-ranks pull request #3
Opened 2018-12-01 22:08 UTC by frinkfromthedrink

Updates this extension to work for beta8

2018-12-01 22:22 UTC, dsevillamartin commented on js/src/forum/index.js
> +import UserCard from 'flarum/components/UserCard'
Why did you import UserCard ?

2018-12-01 22:24 UTC, frinkfromthedrink commented on js/src/forum/index.js
> +import UserCard from 'flarum/components/UserCard'
Sorry, forgot to remove that import, was doing testing locally.

2018-12-01 22:25 UTC, dsevillamartin commented
Fine with me if it works.

2018-12-02 00:06 UTC, KyrneDev requested changes

2018-12-02 00:06 UTC, CDK2020 commented on js/package.json
> +    "name": "@reflar/enso-theme",
🤔

2018-12-02 05:59 UTC, KyrneDev approved these changes

2018-12-02 05:59 UTC, merged